#!/usr/bin/env python3
"""
Generate C++ algorithm reference data using Grok API.
Outputs Python code ready to paste into concpp.py
"""

import os
import sys
import time
import requests
from pathlib import Path
from typing import List, Tuple

# Add scripts directory to path
SCRIPTS_DIR = Path(__file__).parent
sys.path.insert(0, str(SCRIPTS_DIR))

# Import to extract algorithm names
from concpp import ALGORITHMS

# Configuration
CONFIG_FILE = Path("/home/shahar42/Suumerizing_C_holy_grale_book/config/config.env")
PROMPT_FILE = SCRIPTS_DIR / "grok_prompt.txt"
GROK_API_URL = "https://api.x.ai/v1/chat/completions"
MODEL = "grok-4-fast-reasoning"
DELAY = 3  # seconds between API calls


def load_env(file_path: Path) -> dict:
    """Load environment variables from .env file."""
    env = {}
    with open(file_path, 'r') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                key, value = line.split('=', 1)
                env[key.strip()] = value.strip()
    return env


def load_system_prompt() -> str:
    """Load the system prompt for Grok."""
    with open(PROMPT_FILE, 'r') as f:
        return f.read()


def extract_algorithms() -> List[Tuple[str, str]]:
    """Extract all algorithm names and categories from concpp.py."""
    algorithms = []
    for category, algos in ALGORITHMS.items():
        for algo in algos:
            algorithms.append((algo.name, category))
    return algorithms


def query_grok(api_key: str, system_prompt: str, algorithm_name: str) -> str:
    """Query Grok API for algorithm reference."""
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}"
    }

    payload = {
        "model": MODEL,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Generate reference for C++ algorithm: {algorithm_name}"}
        ],
        "temperature": 0.3,  # Lower for more precise/technical output
    }

    try:
        response = requests.post(GROK_API_URL, headers=headers, json=payload, timeout=60)
        response.raise_for_status()
        data = response.json()
        return data['choices'][0]['message']['content']
    except requests.exceptions.RequestException as e:
        print(f"ERROR querying Grok for {algorithm_name}: {e}", file=sys.stderr)
        return None


def main():
    """Main generation loop."""
    # Load configuration
    env = load_env(CONFIG_FILE)
    api_key = env.get('GROK_API_KEY')
    if not api_key:
        print("ERROR: GROK_API_KEY not found in config.env", file=sys.stderr)
        return 1

    # Load system prompt
    system_prompt = load_system_prompt()

    # Extract algorithms
    algorithms = extract_algorithms()
    total = len(algorithms)

    print(f"# Generated by gen_algo_refs.py", file=sys.stderr)
    print(f"# Total algorithms: {total}", file=sys.stderr)
    print(f"# Model: {MODEL}", file=sys.stderr)
    print(f"", file=sys.stderr)

    # Output Python code
    print("# Add to DETAIL_DATA in concpp.py:")
    print()

    success_count = 0
    sample_indices = [1, 5, 10]  # Save these for inspection

    for idx, (algo_name, category) in enumerate(algorithms, 1):
        print(f"# Processing {idx}/{total}: {algo_name} ({category})", file=sys.stderr)

        result = query_grok(api_key, system_prompt, algo_name)

        if result:
            # Output the generated code
            print(result)
            print()
            success_count += 1

            # Save sample outputs for inspection
            if idx in sample_indices:
                sample_file = SCRIPTS_DIR / f"sample_output_{idx}_{algo_name}.py"
                with open(sample_file, 'w') as f:
                    f.write(f"# Sample output {idx}/{total}\n")
                    f.write(f"# Algorithm: {algo_name}\n")
                    f.write(f"# Category: {category}\n\n")
                    f.write(result)
                print(f"# Saved sample to {sample_file.name}", file=sys.stderr)
        else:
            print(f"# FAILED: {algo_name}", file=sys.stderr)
            print(f'# TODO: Manually add reference for "{algo_name}"')
            print()

        # Rate limiting
        if idx < total:
            time.sleep(DELAY)

    print(f"", file=sys.stderr)
    print(f"# Complete: {success_count}/{total} algorithms generated", file=sys.stderr)
    print(f"# Failed: {total - success_count}", file=sys.stderr)

    return 0


if __name__ == '__main__':
    sys.exit(main())
