#!/usr/bin/env python3
"""
Generate C++ iterator reference data using Grok API.
Outputs Python code ready to paste into concpp.py
"""

import os
import sys
import time
import requests
from pathlib import Path
from typing import List, Tuple

# Add scripts directory to path
SCRIPTS_DIR = Path(__file__).parent
sys.path.insert(0, str(SCRIPTS_DIR))

# Import to extract iterator names
from concpp import ITERATORS

# Configuration
CONFIG_FILE = Path("/home/shahar42/Suumerizing_C_holy_grale_book/config/config.env")
PROMPT_FILE = SCRIPTS_DIR / "grok_prompt_iterators.txt"
GROK_API_URL = "https://api.x.ai/v1/chat/completions"
MODEL = "grok-4-fast-reasoning"
DELAY = 3  # seconds between API calls


def load_env(file_path: Path) -> dict:
    """Load environment variables from .env file."""
    env = {}
    with open(file_path, 'r') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                key, value = line.split('=', 1)
                env[key.strip()] = value.strip()
    return env


def load_system_prompt() -> str:
    """Load the system prompt for Grok."""
    with open(PROMPT_FILE, 'r') as f:
        return f.read()


def extract_iterators() -> List[Tuple[str, str]]:
    """Extract all iterator names and categories from concpp.py."""
    iterators = []
    for category, iters in ITERATORS.items():
        for iter_obj in iters:
            iterators.append((iter_obj.name, category))
    return iterators


def query_grok(api_key: str, system_prompt: str, iterator_name: str) -> str:
    """Query Grok API for iterator reference."""
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {api_key}"
    }

    payload = {
        "model": MODEL,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Generate reference for C++ iterator: {iterator_name}"}
        ],
        "temperature": 0.3,  # Lower for more precise/technical output
    }

    try:
        response = requests.post(GROK_API_URL, headers=headers, json=payload, timeout=60)
        response.raise_for_status()
        data = response.json()
        return data['choices'][0]['message']['content']
    except requests.exceptions.RequestException as e:
        print(f"ERROR querying Grok for {iterator_name}: {e}", file=sys.stderr)
        return None


def main():
    """Main generation loop."""
    # Load configuration
    env = load_env(CONFIG_FILE)
    api_key = env.get('GROK_API_KEY')
    if not api_key:
        print("ERROR: GROK_API_KEY not found in config.env", file=sys.stderr)
        return 1

    # Load system prompt
    system_prompt = load_system_prompt()

    # Extract iterators
    iterators = extract_iterators()
    total = len(iterators)

    print(f"# Generated by gen_iter_refs.py", file=sys.stderr)
    print(f"# Total iterators: {total}", file=sys.stderr)
    print(f"# Model: {MODEL}", file=sys.stderr)
    print(f"", file=sys.stderr)

    # Output Python code
    print("# Add to DETAIL_DATA in concpp.py:")
    print()

    success_count = 0
    sample_indices = [1, 5, 10]  # Save these for inspection

    for idx, (iter_name, category) in enumerate(iterators, 1):
        print(f"# Processing {idx}/{total}: {iter_name} ({category})", file=sys.stderr)

        result = query_grok(api_key, system_prompt, iter_name)

        if result:
            # Output the generated code
            print(result)
            print()
            success_count += 1

            # Save sample outputs for inspection
            if idx in sample_indices:
                sample_file = SCRIPTS_DIR / f"sample_iter_{idx}_{iter_name}.py"
                with open(sample_file, 'w') as f:
                    f.write(f"# Sample output {idx}/{total}\n")
                    f.write(f"# Iterator: {iter_name}\n")
                    f.write(f"# Category: {category}\n\n")
                    f.write(result)
                print(f"# Saved sample to {sample_file.name}", file=sys.stderr)
        else:
            print(f"# FAILED: {iter_name}", file=sys.stderr)
            print(f'# TODO: Manually add reference for "{iter_name}"')
            print()

        # Rate limiting
        if idx < total:
            time.sleep(DELAY)

    print(f"", file=sys.stderr)
    print(f"# Complete: {success_count}/{total} iterators generated", file=sys.stderr)
    print(f"# Failed: {total - success_count}", file=sys.stderr)

    return 0


if __name__ == '__main__':
    sys.exit(main())
